version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nhosting
    container_name: nhosting
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/home/app
    networks:
      - nhosting
    ports:
      - 3030:3000

networks:
  nhosting:
    driver: bridge
volumes:
  nhosting-data: