import Head from "next/head";
import CreateAccount from "../components/CreateAccount/CreateAccount";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-5">
      <section>
        <h1 className="text-3xl font-bold underline text-center">nHosting Control Panel</h1>
        
        <CreateAccount />
      </section>
      </main>
      

    </>
  );
}
